// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATAEKew7hpFsmsUpu8V7nkBdphdbI9RBI',
    appId: '1:1035837422902:web:3116429399089664758797',
    messagingSenderId: '1035837422902',
    projectId: 'surplus-plate',
    authDomain: 'surplus-plate.firebaseapp.com',
    storageBucket: 'surplus-plate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDitIRWubVahYxgbscBwl9vT15lIYuQ3gM',
    appId: '1:1035837422902:android:cdcaa8b4aa41126e758797',
    messagingSenderId: '1035837422902',
    projectId: 'surplus-plate',
    storageBucket: 'surplus-plate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU4uBkgSjaq6DYlknHdWRnWevkKQAzJFk',
    appId: '1:1035837422902:ios:9995df51e821c1c5758797',
    messagingSenderId: '1035837422902',
    projectId: 'surplus-plate',
    storageBucket: 'surplus-plate.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU4uBkgSjaq6DYlknHdWRnWevkKQAzJFk',
    appId: '1:1035837422902:ios:9995df51e821c1c5758797',
    messagingSenderId: '1035837422902',
    projectId: 'surplus-plate',
    storageBucket: 'surplus-plate.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATAEKew7hpFsmsUpu8V7nkBdphdbI9RBI',
    appId: '1:1035837422902:web:cf018bf70509ae7c758797',
    messagingSenderId: '1035837422902',
    projectId: 'surplus-plate',
    authDomain: 'surplus-plate.firebaseapp.com',
    storageBucket: 'surplus-plate.firebasestorage.app',
  );
}
